[window]
padding = { x = 6, y = 6 }

[font]
normal = { family = "DejaVu Sans Mono", style = "Regular" }
size = 11

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]
